# version key is obsolete in the latest docker compose version,
# uncomment it if you are using an old version

# version: "3.8"

services:
  db:
    container_name: myWeb_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: myWeb_db
    ports:
      - "5433:5432"
    volumes:
      - myWeb-data:/var/lib/postgresql/myWeb_data
  pgadmin:
    container_name: myWebAdmin_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    volumes:
      - myWebAdmin-data:/var/lib/myWeb_pgadmin
      - ./config_local.py:/pgadmin4/config_local.py

volumes:
  myWeb-data:
  myWebAdmin-data:
